name: Pull Request
'on': pull_request
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Setup Java
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Unit tests
      - name: Unit Tests
        run: ./gradlew :library:testDebugUnitTest
